openapi: 3.0.0
info:
  version: "1.0.0"
  title: API DNS | Implementación DoH
  description: Documentación de la API de DoH de la materia 75.43 Introducción a Sistemas Distribuidos

servers:
  - url: http://localhost:8080/api
    description: Servidor de desarrollo

# Paths servidos por la aplicación
paths:
  /custom-domains:
    get:
      operationId: "api.custom_domains.obtener_todos"
      tags:
        - "Filtrar Custom Domains"
      summary: "Colección filtrada de dominios custom registrados"
      description: "Obtiene la lista de dominios custom registrados que incluyan al string q en su nombre de dominio"
      parameters:
        - in: query
          name: q
          required: false
          description: "Un string utilizado para filtrar los resultados por nombre de dominio"
          schema:
            type: string
      responses:
        200:
          description: "Operación de lectura exitosa"
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: "#/components/schemas/Domain"
    post:
      operationId: "api.custom_domains.crear"
      tags:
        - "Crear Custom Domain"
      summary: "Crea un nuevo Dominio custom"
      description: "Crea un nuevo Dominio custom a partir de un nombre de dominio y una ip. El nombre de dominio debe ser único"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateDomain"
      responses:
        201:
          description: "Se creó el dominio correctamente"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Domain"
        400:
          description: "Nombre de dominio duplicado o request malformado"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"


# Declaración de tipos de datos
components:
  schemas:
    Domain:
      type: object
      properties:
        domain:
          type: string
        ip:
          type: string
        custom:
          type: boolean

    CreateDomain:
      type: object
      properties:
        domain:
          type: string
        ip:
          type: string

    Error:
      type: object
      properties:
        error:
          type: string
