openapi: 3.0.0
info:
  version: "1.0.0"
  title: API DNS | Implementación DoH
  description: Documentación de la API de DoH de la materia 75.43 Introducción a Sistemas Distribuidos

servers:
  - url: http://localhost:8080/api
    description: Servidor de desarrollo

# Paths servidos por la aplicación
paths:
  /domains/{domain_name}:
    get:
      operationId: "api.domains.obtener_uno"
      tags:
        - "Obtener IP para Domain"
      summary: "Obtiene una ip para el dominio consultado"
      description: "Realiza una consulta DNS y devuelve una sola ip para el dominio que se recibió por parámetro.
                    La ip devuelta puede no ser siempre la misma ya que alterna entre las ip de acceso posibles para ese dominio."
      parameters:
        - in: path
          name: domain_name
          required: true
          schema:
            type: string
          description: "Nombre del dominio a consultar"
      responses:
        200:
          description: "Operación de lectura exitosa"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        404:
          description: "Alumno no encontrado"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /custom-domains:
    get:
      operationId: "api.custom_domains.obtener_todos"
      tags:
        - "Filtrar Custom Domains"
      summary: "Colección filtrada de dominios custom registrados"
      description: "Obtiene la lista de dominios custom registrados que incluyan al string q en su nombre de dominio"
      parameters:
        - in: query
          name: q
          required: false
          description: "Un string utilizado para filtrar los resultados por nombre de dominio"
          schema:
            type: string
      responses:
        200:
          description: "Operación de lectura exitosa"
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: "#/components/schemas/Domain"
    post:
      operationId: "api.custom_domains.crear"
      tags:
        - "Crear Custom Domain"
      summary: "Crea un nuevo Dominio custom"
      description: "Crea un nuevo Dominio custom a partir de un nombre de dominio y una ip. El nombre de dominio debe ser único"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateDomain"
      responses:
        201:
          description: "Se creó el dominio correctamente"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Domain"
        400:
          description: "Nombre de dominio duplicado o request malformado"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /custom-domains/{domain_name}:
    put:
      operationId: "api.custom_domains.actualizar"
      tags:
        - "Actualizar Custom Domain"
      summary: "Edita un dominio ya existente en el sistema."
      description: "Edita un dominio ya existente en el sistema."
      parameters:
        - in: path
          name: domain_name
          required: true
          schema:
            type: string
          description: "Nombre del dominio a actualizar"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateDomain"
      responses:
        200:
          description: "Se actualizó el dominio correctamente"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Domain"
        404:
          description: "Nombre de dominio no encontrado"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        400:
          description: "Request malformado"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      operationId: "api.custom_domains.borrar"
      tags:
        - "Borrar Custom Domain"
      summary: "Borra un dominio existente en el sistema."
      description: "Borra un dominio existente en el sistema."
      parameters:
        - in: path
          name: domain_name
          required: true
          schema:
            type: string
          description: "Nombre del dominio a borrar"
      responses:
        200:
          description: "Operación de borrado exitosa"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        404:
          description: "Dominio no encontrado"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"



# Declaración de tipos de datos
components:
  schemas:
    Domain:
      type: object
      properties:
        domain:
          type: string
        ip:
          type: string
        custom:
          type: boolean
          nullable: false

    CreateDomain:
      type: object
      properties:
        domain:
          type: string
        ip:
          type: string

    UpdateDomain:
      type: object
      properties:
        domain:
          type: string
        ip:
          type: string

    Error:
      type: object
      properties:
        error:
          type: string
